import Head from 'next/head';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

import {
	GetStoriesBySearchDocument,
	useCreateStoryMutation,
	useGetStoriesBySearchQuery,
} from '@services/Story.generated';
import { TEST_USER } from '@config/constants';
import { StoryList } from '@components/StoryList';

function Home() {
	const router = useRouter();

	const { data, error, loading } = useGetStoriesBySearchQuery();
	const [createStoryMutationFn, createStoryResult] = useCreateStoryMutation();

	function handleCreateStory() {
		createStoryMutationFn({
			variables: {
				story: {
					title: '',
					author_id: TEST_USER.id,
				},
			},
			refetchQueries: [
				GetStoriesBySearchDocument,
			],
		});
	}

	useEffect(() => {
		if (createStoryResult.called && !createStoryResult.loading && !createStoryResult.error
			&& createStoryResult.data && createStoryResult.data.insert_story_story_one?.id) {
			router.push(`/stories/${createStoryResult.data.insert_story_story_one.id}/edit`);
		}
	}, [createStoryResult]);

	if (error) {
		throw error;
	}

	return (
		<div>
			<Head>
				<title>Smol</title>
				<link rel="icon" href="/favicon.ico" />
				<meta name="description" content="A lightweight medium clone generated by create next app" />
			</Head>

			<main>
				<button type="button" onClick={handleCreateStory}>Write story</button>
				<StoryList
					loading={loading}
					stories={data?.story_story}
				/>
			</main>
		</div>
	);
}

export default Home;
