-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "story"."story" add column "visibility" text
--  not null default 'Draft';
