import Head from 'next/head';
import { useRouter } from 'next/router';

import { StoryEditor } from '@components/StoryEditor';

function Home() {
	const { query } = useRouter();
	const storyId: string | null = query.storyId && !Array.isArray(query.storyId)
		? query.storyId
		: null;

	return (
		<div>
			<Head>
				<title>Smol</title>
				<link rel="icon" href="/favicon.ico" />
				<meta name="description" content="A lightweight medium clone generated by create next app" />
			</Head>

			<main className="flex flex-col items-center">
				{storyId && <StoryEditor storyId={storyId} />}
			</main>
		</div>
	);
}

export default Home;
